name: Feature Request
description: Submit a new feature request
title: ""
labels: []
projects: ["tora-ko-game"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description / 機能の説明
      description: Describe the feature you are requesting / リクエストする機能を説明してください
      placeholder: Describe the new feature...
      value: ""
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority / 優先度
      description: How would you rate the priority of this feature? / この機能の優先度をどのように評価しますか？
      options:
        - Low / 低
        - Medium / 中
        - High / 高
      default: 1
    validations:
      required: true
